services:
  - type: web
    name: florida-schools-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app.server --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0

